'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BranchOffice
    Public Property BranchOfficeId As Integer
    Public Property CompanyId As Integer
    Public Property Name As String
    Public Property Direction As String
    Public Property Phone As String
    Public Property CreationDate As Nullable(Of Date)
    Public Property ModificationDate As Nullable(Of Date)

    Public Overridable Property Company As Company
    Public Overridable Property Checkout As ICollection(Of Checkout) = New HashSet(Of Checkout)

End Class
