'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Caja
    Public Property IdCaja As Integer
    Public Property IdUsuario As Integer
    Public Property IdSucursal As Integer
    Public Property SaldoInicial As Decimal
    Public Property Total As Decimal
    Public Property Fecha As Date

    Public Overridable Property Sucursal As Sucursal
    Public Overridable Property Usuario As Usuario
    Public Overridable Property Factura As ICollection(Of Factura) = New HashSet(Of Factura)
    Public Overridable Property Venta As ICollection(Of Venta) = New HashSet(Of Venta)
    Public Overridable Property Compra As ICollection(Of Compra) = New HashSet(Of Compra)
    Public Overridable Property Pedido As ICollection(Of Pedido) = New HashSet(Of Pedido)

End Class
