'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CashOrder
    Public Property CashOrderId As Integer
    Public Property CustomerId As Integer
    Public Property CheckoutId As Integer
    Public Property CashOrderCode As String
    Public Property OrderDate As Nullable(Of Date)
    Public Property DeliveryDate As Date
    Public Property OrderStatus As Integer
    Public Property Total As Integer
    Public Property CreationDate As Nullable(Of Date)
    Public Property ModificationDate As Nullable(Of Date)

    Public Overridable Property Checkout As Checkout
    Public Overridable Property Customer As Customer
    Public Overridable Property Sale As ICollection(Of Sale) = New HashSet(Of Sale)

End Class
