'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Checkout
    Public Property CheckoutId As Integer
    Public Property ReaderId As Integer
    Public Property BranchOfficeId As Integer
    Public Property Balance As Decimal
    Public Property Total As Decimal
    Public Property CheckoutDate As Date

    Public Overridable Property BranchOffice As BranchOffice
    Public Overridable Property CashOrder As ICollection(Of CashOrder) = New HashSet(Of CashOrder)
    Public Overridable Property Reader As Reader
    Public Overridable Property Invoice As ICollection(Of Invoice) = New HashSet(Of Invoice)
    Public Overridable Property Purchase As ICollection(Of Purchase) = New HashSet(Of Purchase)
    Public Overridable Property Sale As ICollection(Of Sale) = New HashSet(Of Sale)

End Class
