'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cliente
    Public Property IdCliente As Integer
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Correo As String
    Public Property Telefono As String
    Public Property Nit As String
    Public Property Dpi As String

    Public Overridable Property Factura As ICollection(Of Factura) = New HashSet(Of Factura)
    Public Overridable Property Pedido As ICollection(Of Pedido) = New HashSet(Of Pedido)

End Class
