'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Company
    Public Property CompanyId As Integer
    Public Property Name As String
    Public Property Licence As String
    Public Property Pass As String
    Public Property Code As String
    Public Property Branchs As Integer
    Public Property Condition As Boolean
    Public Property CompanyAddress As String
    Public Property Phone As String
    Public Property Email As String
    Public Property Nit As String

    Public Overridable Property BranchOffice As ICollection(Of BranchOffice) = New HashSet(Of BranchOffice)
    Public Overridable Property Equipment As ICollection(Of Equipment) = New HashSet(Of Equipment)
    Public Overridable Property Report As ICollection(Of Report) = New HashSet(Of Report)

End Class
