'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Compra
    Public Property IdCompra As Integer
    Public Property IdProveedor As Integer
    Public Property IdCaja As Integer
    Public Property Fecha As Nullable(Of Date)
    Public Property Total As Integer

    Public Overridable Property Caja As Caja
    Public Overridable Property Producto_Compra As ICollection(Of Producto_Compra) = New HashSet(Of Producto_Compra)
    Public Overridable Property Proveedor As Proveedor

End Class
