'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Customer
    Public Property CustomerId As Integer
    Public Property CustomerCode As String
    Public Property Name As String
    Public Property LastName As String
    Public Property Email As String
    Public Property Phone As String
    Public Property Direction As String
    Public Property Nit As String
    Public Property Dpi As String
    Public Property CreationDate As Nullable(Of Date)
    Public Property ModificationDate As Nullable(Of Date)

    Public Overridable Property CashOrder As ICollection(Of CashOrder) = New HashSet(Of CashOrder)
    Public Overridable Property Invoice As ICollection(Of Invoice) = New HashSet(Of Invoice)

End Class
