'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleado
    Public Property IdEmpleado As Integer
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Correo As String
    Public Property Telefono As String
    Public Property Genero As String
    Public Property Direccion As String
    Public Property Comentario As String
    Public Property Dpi As String

    Public Overridable Property Usuario As ICollection(Of Usuario) = New HashSet(Of Usuario)

End Class
