'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property EmployeeId As Integer
    Public Property Name As String
    Public Property LastName As String
    Public Property Email As String
    Public Property Phone As String
    Public Property Gender As String
    Public Property Direction As String
    Public Property Comment As String
    Public Property Dpi As String
    Public Property BirthDate As Nullable(Of Date)
    Public Property CreationDate As Nullable(Of Date)
    Public Property ModificationDate As Nullable(Of Date)

    Public Overridable Property Reader As ICollection(Of Reader) = New HashSet(Of Reader)

End Class
