'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Factura
    Public Property IdFactura As Integer
    Public Property IdCliente As Integer
    Public Property IdCaja As Integer
    Public Property NoFactura As String
    Public Property Serie As String
    Public Property Fecha As Nullable(Of Date)
    Public Property Descripcion As String
    Public Property Total As Nullable(Of Decimal)

    Public Overridable Property Caja As Caja
    Public Overridable Property Cliente As Cliente
    Public Overridable Property Producto_Factura As ICollection(Of Producto_Factura) = New HashSet(Of Producto_Factura)

End Class
