'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Producto_Compra
    Public Property IdCompra As Integer
    Public Property IdProducto As Integer
    Public Property Cantidad As Integer
    Public Property Precio As Decimal

    Public Overridable Property Compra As Compra
    Public Overridable Property Producto As Producto

End Class
