'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product_Sale
    Public Property ProductId As Integer
    Public Property SaleId As Integer
    Public Property Amount As Nullable(Of Integer)
    Public Property Price As Decimal

    Public Overridable Property Product As Product
    Public Overridable Property Sale As Sale

End Class
