'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product_Purchase
    Public Property PurchaseId As Integer
    Public Property ProductId As Integer
    Public Property Amount As Integer
    Public Property Price As Decimal

    Public Overridable Property Product As Product
    Public Overridable Property Purchase As Purchase

End Class
