'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Provider
    Public Property ProviderId As Integer
    Public Property ProviderCode As String
    Public Property BusinessName As String
    Public Property PrincipalAddress As String
    Public Property Direction As String
    Public Property Phone As String
    Public Property Pbx As String
    Public Property Email As String
    Public Property Nit As String
    Public Property WebPage As String
    Public Property Explanation As String
    Public Property CreationDate As Nullable(Of Date)
    Public Property ModificationDate As Nullable(Of Date)

    Public Overridable Property Purchase As ICollection(Of Purchase) = New HashSet(Of Purchase)

End Class
