'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Purchase
    Public Property PurchaseId As Integer
    Public Property ProviderId As Integer
    Public Property CheckoutId As Integer
    Public Property PurchaseDate As Nullable(Of Date)
    Public Property Total As Integer

    Public Overridable Property Checkout As Checkout
    Public Overridable Property Product_Purchase As ICollection(Of Product_Purchase) = New HashSet(Of Product_Purchase)
    Public Overridable Property Provider As Provider

End Class
