'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Reader
    Public Property ReaderId As Integer
    Public Property RolId As Integer
    Public Property EmployeeId As Integer
    Public Property Nick As String
    Public Property Pass As String
    Public Property CreationDate As Nullable(Of Date)
    Public Property ModificationDate As Nullable(Of Date)

    Public Overridable Property Checkout As ICollection(Of Checkout) = New HashSet(Of Checkout)
    Public Overridable Property Employee As Employee
    Public Overridable Property Inventory As ICollection(Of Inventory) = New HashSet(Of Inventory)
    Public Overridable Property Rol As Rol

End Class
