'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Rol
    Public Property RolId As Integer
    Public Property Name As String
    Public Property Explanation As String

    Public Overridable Property Reader As ICollection(Of Reader) = New HashSet(Of Reader)
    Public Overridable Property [Module] As ICollection(Of [Module]) = New HashSet(Of [Module])

End Class
