'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sale
    Public Property SaleId As Integer
    Public Property CashOrderId As Integer
    Public Property CheckoutId As Integer
    Public Property SaleDate As Nullable(Of Date)

    Public Overridable Property CashOrder As CashOrder
    Public Overridable Property Checkout As Checkout
    Public Overridable Property Product_Sale As ICollection(Of Product_Sale) = New HashSet(Of Product_Sale)

End Class
