'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DbInventarioEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DbInventarioEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Caja() As DbSet(Of Caja)
    Public Property Categoria() As DbSet(Of Categoria)
    Public Property Cliente() As DbSet(Of Cliente)
    Public Property Compra() As DbSet(Of Compra)
    Public Property Empleado() As DbSet(Of Empleado)
    Public Property Empresa() As DbSet(Of Empresa)
    Public Property Equipo() As DbSet(Of Equipo)
    Public Property Factura() As DbSet(Of Factura)
    Public Property Inventario() As DbSet(Of Inventario)
    Public Property Modulo() As DbSet(Of Modulo)
    Public Property Pedido() As DbSet(Of Pedido)
    Public Property Producto() As DbSet(Of Producto)
    Public Property Producto_Compra() As DbSet(Of Producto_Compra)
    Public Property Producto_Factura() As DbSet(Of Producto_Factura)
    Public Property Producto_Inventario() As DbSet(Of Producto_Inventario)
    Public Property Proveedor() As DbSet(Of Proveedor)
    Public Property Reporte() As DbSet(Of Reporte)
    Public Property Rol() As DbSet(Of Rol)
    Public Property Sucursal() As DbSet(Of Sucursal)
    Public Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Property Usuario() As DbSet(Of Usuario)
    Public Property Venta() As DbSet(Of Venta)

End Class
