'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class InventarioDemoEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=InventarioDemoEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property BranchOffice() As DbSet(Of BranchOffice)
    Public Overridable Property CashOrder() As DbSet(Of CashOrder)
    Public Overridable Property Category() As DbSet(Of Category)
    Public Overridable Property Checkout() As DbSet(Of Checkout)
    Public Overridable Property Company() As DbSet(Of Company)
    Public Overridable Property Customer() As DbSet(Of Customer)
    Public Overridable Property Employee() As DbSet(Of Employee)
    Public Overridable Property Equipment() As DbSet(Of Equipment)
    Public Overridable Property Inventory() As DbSet(Of Inventory)
    Public Overridable Property Invoice() As DbSet(Of Invoice)
    Public Overridable Property [Module]() As DbSet(Of [Module])
    Public Overridable Property Product() As DbSet(Of Product)
    Public Overridable Property Product_Inventory() As DbSet(Of Product_Inventory)
    Public Overridable Property Product_Purchase() As DbSet(Of Product_Purchase)
    Public Overridable Property Product_Sale() As DbSet(Of Product_Sale)
    Public Overridable Property Provider() As DbSet(Of Provider)
    Public Overridable Property Purchase() As DbSet(Of Purchase)
    Public Overridable Property Reader() As DbSet(Of Reader)
    Public Overridable Property Report() As DbSet(Of Report)
    Public Overridable Property Rol() As DbSet(Of Rol)
    Public Overridable Property Sale() As DbSet(Of Sale)

End Class
