'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Sucursal
    Public Property IdSucursal As Integer
    Public Property IdEmpresa As Integer
    Public Property Nombre As String
    Public Property Ubicacion As String
    Public Property Telefono As Integer

    Public Overridable Property Caja As ICollection(Of Caja) = New HashSet(Of Caja)
    Public Overridable Property Empresa As Empresa

End Class
