'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario
    Public Property IdUsuario As Integer
    Public Property IdRol As Integer
    Public Property IdEmpleado As Integer
    Public Property Nick As String
    Public Property Pass As String

    Public Overridable Property Caja As ICollection(Of Caja) = New HashSet(Of Caja)
    Public Overridable Property Empleado As Empleado
    Public Overridable Property Inventario As ICollection(Of Inventario) = New HashSet(Of Inventario)
    Public Overridable Property Rol As Rol

End Class
